name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2  # Updated to v2
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Install Dependencies
      run: npm install  # If your site needs build steps like npm install
      working-directory: ./frontend  # Update this to your project's path if needed

    - name: Build static site
      run: npm run build  # Add this if you need to build your site

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./lipo s3://lipofuscin.yalepages.org --delete --exclude "*.git*/*"  # Change `./build` to your build directory if different
    - name: Flush Distribution Cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.DISTRIBUTION_ID }} --paths '/*'
